name       : fcitx-hangul
version    : 0.3.1
release    : 2
source     :
    - https://download.fcitx-im.org/fcitx-hangul/fcitx-hangul-0.3.1.tar.xz : 6dd5fd5956924c85af92ebefaef1e113e38fa814355fbb0f07c26049c3014437
license    : GPL-2.0-or-later
component  : desktop.core
summary    : Hangul (Korean) support for fcitx
description: |
    Hangul is a input method for Korean and also it provides ability to type with Hanja.
builddeps  :
    - pkgconfig(fcitx)
    - pkgconfig(libhangul)
    - intltool
rundeps    :
    - fcitx
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
